name: Link Checker (lychee)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --accept 200,206,429 --timeout 20 --max-redirects 5 --include-fragments './**/*.html' './**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

